### ISSUE TITLE
Registry Error

### ISSUE THREAD

**Issue by Mesamec** [WhiskyTangoFawks/WTFCore#2]
Attempting to join a server I host that is running the pack All the Mods v1.12 throws this error for me every time and disconnects me, error line here: 

`java.lang.IllegalArgumentException: The object class wtf.core.blocks.BlockWTFTorch (minecraft:torch) cannot be added to the registry. It is already being used as a substitute for minecraft:torch` 

Full relevant section from fml-client-latest logs [here](http://pastebin.com/d0NB5UL8).

**Comment by WhiskyTangoFawks** [comment]
I've tested it on a server, and in a much smaller modpack it works just fine for me.  Based on the log, I suspect that the forge version you're using is out of date, try updating to the latest version and see if it fixes it.  If there's still a problem on the latest version of forge, then it's probably an incompatibility with another mod in the pack, and without knowing which one and why there's not much I can do on my end.  As a workaround though, you can disable the torch feature, which should get around the issue.

**Comment by Mesamec** [comment]
Tested on an otherwise clean Minecraft setup with forge 12.18.1.2065, same issue occurs when attempting to connect to a server. Downgrading forge to 2050 does fix the issue.

**Comment by WhiskyTangoFawks** [comment]
I was able to replicate the issue, and think the latest version Beta9.2 should fix this.
